name: target
run-name: "${{ inputs.target }}"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target (e.g. rust-lang/rust/static-bound)'
        required: true
        type: string
      x86_64-linux:
        description: "Run on x86_64-linux"
        type: boolean
        default: true
      aarch64-linux:
        description: "Run on aarch64-linux"
        type: boolean
        default: true
      x86_64-darwin:
        description: "Run on x86_64-darwin"
        type: boolean
        default: true
      aarch64-darwin:
        description: "Run on aarch64-darwin"
        type: boolean
        default: true
      upterm:
        description: "Start upterm session after failure"
        type: boolean
        default: false

jobs:
  x86_64-linux:
    if: ${{ inputs.x86_64-linux }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh ./scripts/target ${{ inputs.target }}
      - uses: owenthereal/action-upterm@v1
        if: ${{ failure() && inputs.upterm }}
        with:
          limit-access-to-actor: true

  aarch64-linux:
    if: ${{ inputs.aarch64-linux }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: sh ./scripts/target ${{ inputs.target }}
      - uses: owenthereal/action-upterm@v1
        if: ${{ failure() && inputs.upterm }}
        with:
          limit-access-to-actor: true

  x86_64-darwin:
    if: ${{ inputs.x86_64-darwin }}
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
      - run: sh ./scripts/target ${{ inputs.target }}
      - uses: owenthereal/action-upterm@v1
        if: ${{ failure() && inputs.upterm }}
        with:
          limit-access-to-actor: true

  aarch64-darwin:
    if: ${{ inputs.aarch64-darwin }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh ./scripts/target ${{ inputs.target }}
      - uses: owenthereal/action-upterm@v1
        if: ${{ failure() && inputs.upterm }}
        with:
          limit-access-to-actor: true
