name: test
run-name: "${{ inputs.target }}"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target (e.g. rust-lang/rust/static-bound)'
        required: true
        type: string
      x86_64-linux:
        description: "Run on x86_64-linux"
        type: boolean
        default: true
      aarch64-linux:
        description: "Run on aarch64-linux"
        type: boolean
        default: true
      x86_64-darwin:
        description: "Run on x86_64-darwin"
        type: boolean
        default: true
      aarch64-darwin:
        description: "Run on aarch64-darwin"
        type: boolean
        default: true

jobs:
  x86_64-linux:
    if: ${{ inputs.x86_64-linux }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh ./runner ${{ inputs.target }}

  aarch64-linux:
    if: ${{ inputs.aarch64-linux }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: sh ./runner ${{ inputs.target }}

  x86_64-darwin:
    if: ${{ inputs.x86_64-darwin }}
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
      - run: sh ./runner ${{ inputs.target }}

  aarch64-darwin:
    if: ${{ inputs.aarch64-darwin }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh ./runner ${{ inputs.target }}
